name: build

on:
  push:
    branches:
      - "main"
    tags:
      - "!*"
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: macOS-11
    steps:
    - uses: actions/checkout@v1
    - name: Build Package
      run: |
        xcodebuild -scheme $SCHEME -destination $DESTINATION | xcpretty
      env:
        SCHEME: SCNLine
        DESTINATION: generic/platform=iOS
